### ISSUE TITLE
incompatibility with levelz

### ISSUE THREAD

**Issue by MrOz59** [Minenash/ActionHunger#3]
Both mods mess with the hunger bar, so it ends up giving this error, if you could make a compatible version it would be incredible.

When creating a world the game crashes, and Mixin Conflict Helper shows this error:

[LevelZ](https://github.com/Globox1997/LevelZ) is conflicting with [ActionHunger](https://github.com/Minenash/ActionHunger).

## Stacktrace
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1702::updateStaminaMixin with priority 1000 cannot inject into net/minecraft/class_1702::method_7588(Lnet/minecraft/class_1657;)V merged by com.minenash.action_hunger.mixin.HungerManagerMixin with priority 1000 [PREINJECT Applicator Phase -> levelz.mixins.json:player.HungerManagerMixin from mod levelz -> Prepare Injections ->  -> handler$gca000$levelz$updateStaminaMixin(Lnet/minecraft/class_1657;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_1657.<init>(class_1657.java:168)
	at net.minecraft.class_3222.<init>(class_3222.java:266)
	at net.minecraft.class_3324.method_14613(class_3324.java:479)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$ecc000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063)
	at net.minecraft.class_3248.method_18784(class_3248.java:68)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

## Mod versions
```
- action_hunger 0.2.0+1.20
- levelz 1.4.11
- libz 1.0.3


## Game info
Minecraft Version: 1.20.1
Fabric Loader Version: 0.14.25

**Comment by Minenash** [comment]
If I remember how mixins priorities work, I believe fixing the crash is easy.

However, assuming you want to keep the functionality, I'm not 100% sure how I would go about it. Since this mod changes so much if how hunger and saturation works, it overwrites the update method entirely

**Comment by MrOz59** [comment]
levelz has a specific level for hunger, which reduces exhaustion and increases regeneration at each level, it would be cool if the two mods could work together to make this status more useful, for example, if you have maximum level in this attribute, if the your hunger bar is full you get some buff like strength, or something like that, just an idea

 I don't understand almost anything about mod configuration, so if there's any way to make both work, even if you have to remove this attribute from levelz, I'd love to know. 

thanks for the reply
